"""added subtotal on order Model

Revision ID: 131baac80a9a
Revises: d6833dd6b01a
Create Date: 2025-10-02 19:14:48.806045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131baac80a9a'
down_revision: Union[str, None] = 'd6833dd6b01a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('sub_total', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('total_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_price')
    op.drop_column('orders', 'sub_total')
    # ### end Alembic commands ###
