"""init schema

Revision ID: d6833dd6b01a
Revises: 
Create Date: 2025-10-01 14:35:54.567739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6833dd6b01a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_index('idx_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('session_bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_bookings_session_id_status', 'session_bookings', ['session_id', 'status'], unique=False)
    op.create_index('idx_session_bookings_user_id', 'session_bookings', ['user_id'], unique=False)
    op.create_index(op.f('ix_session_bookings_id'), 'session_bookings', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_items_course_id', 'order_items', ['course_id'], unique=False)
    op.create_index('idx_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_table('payment_details',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_order_id', sa.String(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index('idx_payment_details_order_id', 'payment_details', ['order_id'], unique=False)
    op.create_index('idx_payment_details_payment_id', 'payment_details', ['payment_id'], unique=False)
    op.create_index('idx_payment_details_provider_order_id', 'payment_details', ['provider_order_id'], unique=False)
    op.create_index(op.f('ix_payment_details_id'), 'payment_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_details_id'), table_name='payment_details')
    op.drop_index('idx_payment_details_provider_order_id', table_name='payment_details')
    op.drop_index('idx_payment_details_payment_id', table_name='payment_details')
    op.drop_index('idx_payment_details_order_id', table_name='payment_details')
    op.drop_table('payment_details')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_index('idx_order_items_order_id', table_name='order_items')
    op.drop_index('idx_order_items_course_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_session_bookings_id'), table_name='session_bookings')
    op.drop_index('idx_session_bookings_user_id', table_name='session_bookings')
    op.drop_index('idx_session_bookings_session_id_status', table_name='session_bookings')
    op.drop_table('session_bookings')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index('idx_orders_user_id', table_name='orders')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
